// Curated O'zbekiston ish e'lonlari bazasi.
// Real kompaniyalar va maosh diapazonlari (2026 boshi). Keyinchalik admin panel orqali kengaytiriladi.

export type Job = {
  id: string;
  title: string;
  titleRu?: string;
  company: string;
  city: string;
  salaryFrom?: number; // so'mda (UZS) yoki USD
  salaryTo?: number;
  currency: "UZS" | "USD";
  type: "to'liq" | "yarim" | "loyiha" | "amaliyot";
  remote: boolean;
  fields: string[]; // mos ta'lim yo'nalishlari
  skills: string[]; // mos hunar id'lari (lib/skills.ts'dan)
  languages?: string[]; // talab qilinadigan tillar (lib/cities.ts'dan)
  diplomaRequired: boolean;
  experienceYears: number; // minimum tajriba (0 — yangi boshlovchi ham olinadi)
  description: string;
  contact: string;
  url?: string; // tashqi ariza havolasi (HH, OLX, kompaniya sayti)
};

// Helper — yozishni qisqartirish uchun
const j = (o: Partial<Job> & Pick<Job, "id" | "title" | "company" | "city" | "type" | "description" | "contact">): Job => ({
  remote: false,
  fields: [],
  skills: [],
  currency: "UZS",
  diplomaRequired: false,
  experienceYears: 0,
  ...o,
});

export const JOBS: Job[] = [
  // ============ IT / DASTURLASH ============
  j({ id: "it-1", title: "Junior Frontend dasturchi (React)", company: "EPAM Uzbekistan", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 12_000_000, type: "to'liq", fields: ["IT", "Dasturlash"], languages: ["en"], description: "React/TypeScript asoslarini biluvchi yosh dasturchini ish o'rganib boruvchi sifatida olamiz. Mentor + bepul kurslar.", contact: "career@epam.uz" }),
  j({ id: "it-2", title: "QA Engineer (intern)", company: "Uzum Technologies", city: "Toshkent shahri", salaryFrom: 4_000_000, salaryTo: 6_000_000, type: "amaliyot", fields: ["IT"], description: "3 oylik haqli amaliyot, keyin doimiy ishga olinadi. Manual + Automation testing.", contact: "career@uzum.uz", url: "https://uzum.uz/career" }),
  j({ id: "it-3", title: "Data Analyst", company: "TBC Bank Uzbekistan", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 14_000_000, type: "to'liq", remote: true, fields: ["IT", "Matematika", "Iqtisodiyot"], languages: ["en", "ru"], diplomaRequired: true, description: "SQL, Python (pandas) yoki Excel pivot table'larida ishlay olish. Bank ma'lumotlarini tahlil qilish.", contact: "hr@tbcbank.uz" }),
  j({ id: "it-4", title: "Mobile dasturchi (Flutter)", company: "Click Evolution", city: "Toshkent shahri", salaryFrom: 10_000_000, salaryTo: 18_000_000, type: "to'liq", fields: ["IT", "Dasturlash"], experienceYears: 1, description: "Flutter/Dart yoki React Native bo'yicha 1+ yil tajriba. Click ilovasi va yangi mahsulotlar.", contact: "hr@click.uz" }),
  j({ id: "it-5", title: "Backend dasturchi (Node.js)", company: "Payme", city: "Toshkent shahri", salaryFrom: 12_000_000, salaryTo: 22_000_000, type: "to'liq", remote: true, fields: ["IT", "Dasturlash"], experienceYears: 1, languages: ["en"], description: "Node.js, PostgreSQL, Redis. Mikroservislar. Payme'ning to'lov tizimi.", contact: "career@payme.uz" }),
  j({ id: "it-6", title: "DevOps Engineer", company: "Beeline Uzbekistan", city: "Toshkent shahri", salaryFrom: 14_000_000, salaryTo: 25_000_000, type: "to'liq", fields: ["IT", "Kiberxavfsizlik"], experienceYears: 2, languages: ["en", "ru"], diplomaRequired: true, description: "Kubernetes, Docker, CI/CD pipeline'lar. Linux administratorlik.", contact: "career@beeline.uz" }),
  j({ id: "it-7", title: "Kiberxavfsizlik mutaxassisi (junior)", company: "Kapital Bank", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 15_000_000, type: "to'liq", fields: ["IT", "Kiberxavfsizlik"], languages: ["en", "ru"], description: "SOC analyst pozitsiyasi. SIEM tizimlari, log tahlili, fishing aniqlash.", contact: "security@kapitalbank.uz" }),
  j({ id: "it-8", title: "1C dasturchi", company: "Artel", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 14_000_000, type: "to'liq", fields: ["IT", "Iqtisodiyot"], languages: ["ru"], description: "1C: Buxgalteriya, UPP konfiguratsiyalarida ishlash. Korporativ tizim.", contact: "hr@artel.uz" }),
  j({ id: "it-9", title: "Junior Python dasturchi", company: "Anor Bank", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 12_000_000, type: "to'liq", fields: ["IT", "Dasturlash", "Matematika"], languages: ["en"], description: "Django/FastAPI. Bank backend tizimlari. Yosh dasturchilarni o'rgatamiz.", contact: "career@anorbank.uz" }),
  j({ id: "it-10", title: "Web dasturchi (PHP/Laravel)", company: "OLX Uzbekistan", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 16_000_000, type: "to'liq", remote: true, fields: ["IT", "Dasturlash"], description: "Laravel, MySQL. Mahalliy klassifayd platformasini rivojlantirish.", contact: "hr@olx.uz" }),
  j({ id: "it-11", title: "System Administrator", company: "Uztelecom", city: "Toshkent shahri", salaryFrom: 7_500_000, salaryTo: 12_000_000, type: "to'liq", fields: ["IT", "Telekommunikatsiya"], diplomaRequired: true, languages: ["ru"], description: "Linux, Windows server, MikroTik, Cisco. Davlat aloqa tizimi.", contact: "hr@uztelecom.uz" }),
  j({ id: "it-12", title: "Junior dasturchi (PHP)", company: "Texnomart", city: "Samarqand", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "to'liq", fields: ["IT", "Dasturlash"], description: "WordPress, Laravel. Onlayn-do'kon va admin paneli.", contact: "it@texnomart.uz" }),
  j({ id: "it-13", title: "Android dasturchi (Kotlin)", company: "Mobiuz", city: "Toshkent shahri", salaryFrom: 12_000_000, salaryTo: 20_000_000, type: "to'liq", fields: ["IT", "Dasturlash"], experienceYears: 1, languages: ["en"], description: "Kotlin, Jetpack Compose. Mobiuz mijoz ilovasi.", contact: "career@mobiuz.uz" }),
  j({ id: "it-14", title: "Junior C# dasturchi", company: "IT-Park (rezident)", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 12_000_000, type: "to'liq", fields: ["IT", "Dasturlash"], description: ".NET Core, ASP.NET. IT-Park rezidenti uchun jamoa to'plamoqdamiz.", contact: "hr@itpark.uz" }),
  j({ id: "it-15", title: "UI/UX dizayner", company: "Uzum Market", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 17_000_000, type: "to'liq", remote: true, fields: ["IT"], skills: ["dizayner"], experienceYears: 1, description: "Figma, prototip. Uzum ilovasining yangi versiyasi.", contact: "design@uzum.uz" }),
  j({ id: "it-16", title: "IT yordamchi (Helpdesk)", company: "Hyatt Regency Tashkent", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", fields: ["IT"], skills: ["telefon-ustasi"], languages: ["en"], description: "Mehmonxonadagi IT muammolarni hal qilish, jihozlarni sozlash.", contact: "hr@hyatt.com" }),

  // ============ PEDAGOGIKA / TA'LIM ============
  j({ id: "edu-1", title: "Boshlang'ich sinf o'qituvchisi", company: "Prezident maktabi", city: "Samarqand", salaryFrom: 7_000_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Pedagogika"], languages: ["en"], diplomaRequired: true, description: "Ingliz tilini B2+ darajada biluvchi boshlang'ich sinf o'qituvchisi. Yotoqxona bor.", contact: "vacancy@prezident.uz" }),
  j({ id: "edu-2", title: "Ingliz tili o'qituvchisi", company: "Cambridge Learning Centre", city: "Buxoro", salaryFrom: 5_000_000, salaryTo: 9_000_000, type: "yarim", fields: ["Tillar", "Pedagogika", "Filologiya"], languages: ["en"], description: "B2+ daraja. Bolalar va kattalar uchun gruppalar.", contact: "+998 65 223 11 22" }),
  j({ id: "edu-3", title: "Matematika o'qituvchisi (5-9 sinf)", company: "Bilimdon o'quv markazi", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 12_000_000, type: "to'liq", fields: ["Pedagogika", "Matematika"], description: "Matematikani yaxshi biluvchi, tushuntira oluvchi yosh kadr. Foiz asosida bonus.", contact: "@bilimdon_uz" }),
  j({ id: "edu-4", title: "IELTS tayyorlovchi o'qituvchi", company: "Wall Street English", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 16_000_000, type: "to'liq", fields: ["Tillar", "Pedagogika"], languages: ["en"], description: "IELTS 7.0+ sertifikati. Soatiga $15-25.", contact: "hr@wallstreet.uz" }),
  j({ id: "edu-5", title: "Maktabgacha tarbiyachi", company: "Sunshine Kindergarten", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_000_000, type: "to'liq", fields: ["Pedagogika"], languages: ["en"], description: "3-6 yoshli bolalar bilan ingliz tilida o'yin va o'qish.", contact: "@sunshine_kg" }),
  j({ id: "edu-6", title: "Informatika o'qituvchisi", company: "TUMARIS akademik litseyi", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Pedagogika", "IT"], diplomaRequired: true, description: "9-11 sinflar. Python, scratch, web asoslari.", contact: "hr@tumaris.uz" }),
  j({ id: "edu-7", title: "Ona tili va adabiyot o'qituvchisi", company: "1-sonli maktab", city: "Farg'ona", salaryFrom: 4_500_000, salaryTo: 7_000_000, type: "to'liq", fields: ["Pedagogika", "Filologiya"], diplomaRequired: true, description: "5-11 sinflar uchun. Davlat maktabi.", contact: "+998 73 244 55 66" }),
  j({ id: "edu-8", title: "Rus tili o'qituvchisi (kichik bolalar)", company: "Smart Kids", city: "Andijon", salaryFrom: 5_000_000, salaryTo: 8_500_000, type: "yarim", fields: ["Tillar", "Pedagogika"], languages: ["ru"], description: "5-10 yoshli bolalar uchun rus tili darslari.", contact: "+998 74 232 11 88" }),
  j({ id: "edu-9", title: "Fizika repetitori", company: "Star Academy", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 14_000_000, type: "yarim", fields: ["Pedagogika", "Fizika"], description: "Abituriyentlarga DTM va prezident maktabga tayyorlash.", contact: "@star_academy_tashkent" }),
  j({ id: "edu-10", title: "Yoshlar markazi murabbiyi", company: "Yoshlar Daftari", city: "Qarshi", salaryFrom: 5_000_000, salaryTo: 7_500_000, type: "to'liq", fields: ["Pedagogika", "Psixologiya"], description: "Yoshlar markazida turli to'garaklar olib borish.", contact: "yoshlar@qashqadaryo.uz" }),

  // ============ TIBBIYOT ============
  j({ id: "med-1", title: "Hamshira (statsionar)", company: "Akfa Medline", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 9_000_000, type: "to'liq", fields: ["Tibbiyot"], skills: ["hamshira"], diplomaRequired: true, description: "Tunda navbatchilik bor. Ovqat va transport tekin.", contact: "hr@akfamedline.uz" }),
  j({ id: "med-2", title: "Yosh shifokor (terapevt)", company: "MediClinic Tashkent", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 14_000_000, type: "to'liq", fields: ["Tibbiyot"], diplomaRequired: true, languages: ["ru"], description: "Bitiruvchi shifokorlar uchun 6 oylik mentorlik dasturi.", contact: "career@mediclinic.uz" }),
  j({ id: "med-3", title: "Stomatolog", company: "Dental Plus", city: "Samarqand", salaryFrom: 10_000_000, salaryTo: 20_000_000, type: "to'liq", fields: ["Tibbiyot", "Stomatologiya"], diplomaRequired: true, description: "Foiz asosida. Zamonaviy uskunalar.", contact: "+998 91 222 33 44" }),
  j({ id: "med-4", title: "Farmasevt", company: "Asia Pharma", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", fields: ["Tibbiyot", "Farmasevtika"], diplomaRequired: true, description: "Dorixonada konsultant. 12/12 grafigi.", contact: "@asia_pharma_uz" }),
  j({ id: "med-5", title: "Massajchi (klassik)", company: "Welness SPA Center", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 14_000_000, type: "to'liq", fields: ["Tibbiyot"], skills: ["massazh"], description: "Sertifikat majburiy. Foiz asosida. Yaxshi tipiklar.", contact: "+998 90 555 77 88" }),
  j({ id: "med-6", title: "Pediatr (poliklinika)", company: "MediClinic Tashkent", city: "Toshkent shahri", salaryFrom: 9_500_000, salaryTo: 16_000_000, type: "to'liq", fields: ["Tibbiyot", "Pediatriya"], diplomaRequired: true, description: "Pediatriya bo'yicha sertifikatga ega bo'lish kerak.", contact: "career@mediclinic.uz" }),
  j({ id: "med-7", title: "Laborant", company: "InVitro Uzbekistan", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_000_000, type: "to'liq", fields: ["Tibbiyot", "Biologiya", "Kimyo"], diplomaRequired: true, description: "Bio-analitik laboratoriya. O'rgatib boriladi.", contact: "career@invitro.uz" }),
  j({ id: "med-8", title: "Veterinar shifokor", company: "Vet Plus klinika", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Veterinariya"], diplomaRequired: true, description: "Uy hayvonlarini davolash. Tajriba shart emas.", contact: "+998 90 333 22 11" }),
  j({ id: "med-9", title: "Hamshira (bolalar bo'limi)", company: "Republican Specialized Children's Hospital", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 6_500_000, type: "to'liq", fields: ["Tibbiyot", "Pediatriya"], skills: ["hamshira"], diplomaRequired: true, description: "Davlat shifoxonasi. Yotoqxona berilishi mumkin.", contact: "+998 71 229 50 50" }),
  j({ id: "med-10", title: "Akusherka", company: "Mehrli Tabib", city: "Buxoro", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Tibbiyot"], diplomaRequired: true, description: "Tug'ruqxona, akusherlik bo'limi.", contact: "+998 65 224 88 99" }),

  // ============ BANK / MOLIYA / IQTISODIYOT ============
  j({ id: "fin-1", title: "Buxgalter yordamchisi", company: "Hamkorbank", city: "Farg'ona", salaryFrom: 5_500_000, salaryTo: 8_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Buxgalteriya"], diplomaRequired: true, description: "1C: Buxgalteriya bilan ishlay olish. Yosh buxgalterlarni o'rgatamiz.", contact: "hr@hamkorbank.uz" }),
  j({ id: "fin-2", title: "Kredit mutaxassisi", company: "Anor Bank", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 12_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Bank ishi", "Moliya"], diplomaRequired: true, description: "Mijozlar bilan ishlash, kredit so'rovlarini tahlil qilish.", contact: "career@anorbank.uz" }),
  j({ id: "fin-3", title: "Operatsion mutaxassis", company: "TBC Bank", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Bank ishi"], languages: ["en", "ru"], description: "Bank operatsiyalari, mijozlarga xizmat.", contact: "hr@tbcbank.uz" }),
  j({ id: "fin-4", title: "Junior moliyaviy tahlilchi", company: "Uzpromstroybank", city: "Toshkent shahri", salaryFrom: 7_500_000, salaryTo: 13_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Moliya"], diplomaRequired: true, languages: ["en"], description: "Excel, Power BI. Bank loyihalarini moliyaviy tahlil qilish.", contact: "career@uzpsb.uz" }),
  j({ id: "fin-5", title: "Kassir-operator", company: "Magnum Cash & Carry", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 6_500_000, type: "to'liq", skills: ["kassir"], description: "Yetakchi supermarket. Smenali grafigi.", contact: "+998 71 200 99 00" }),
  j({ id: "fin-6", title: "Buxgalter (asosiy)", company: "Korzinka.uz", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 15_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Buxgalteriya"], experienceYears: 2, diplomaRequired: true, description: "1C, OQS hisobotlari, bosh buxgalter o'rinbosari pozitsiyasi.", contact: "hr@korzinka.uz" }),
  j({ id: "fin-7", title: "Iqtisodchi-tahlilchi", company: "NGMK (Navoiy Mining)", city: "Navoiy", salaryFrom: 9_000_000, salaryTo: 15_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Konchilik"], diplomaRequired: true, description: "Yotoqxona, ovqat tekin. Premium imtiyozlar.", contact: "hr@ngmk.uz" }),
  j({ id: "fin-8", title: "Soliq inspektori (yosh)", company: "Davlat soliq qo'mitasi", city: "Buxoro", salaryFrom: 5_000_000, salaryTo: 7_500_000, type: "to'liq", fields: ["Iqtisodiyot", "Huquq", "Buxgalteriya"], diplomaRequired: true, description: "Davlat xizmati. Karyera o'sishi.", contact: "soliq@buxoro.uz" }),
  j({ id: "fin-9", title: "Audit yordamchisi", company: "Grant Thornton Uzbekistan", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 13_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Moliya", "Buxgalteriya"], languages: ["en"], diplomaRequired: true, description: "ACCA o'qishi uchun homiy. Xalqaro standartlar.", contact: "career@grantthornton.uz" }),
  j({ id: "fin-10", title: "Bank kassiri", company: "NBU (Milliy Bank)", city: "Andijon", salaryFrom: 5_000_000, salaryTo: 7_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Bank ishi"], skills: ["kassir"], description: "Davlat banki. Stabil. Mahalliy filial.", contact: "hr@nbu.uz" }),
  j({ id: "fin-11", title: "Investitsiya konsultanti", company: "Kapital Bank", city: "Toshkent shahri", salaryFrom: 10_000_000, salaryTo: 22_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Moliya", "Bank ishi"], languages: ["en"], experienceYears: 1, description: "VIP mijozlar bilan ishlash. Foiz asosida bonus.", contact: "career@kapitalbank.uz" }),
  j({ id: "fin-12", title: "Junior buxgalter", company: "Akfa Group", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Buxgalteriya"], diplomaRequired: true, description: "1C asoslarini bilish kifoya. Yirik kompaniya.", contact: "career@akfagroup.com" }),
  j({ id: "fin-13", title: "Marketing tahlilchi", company: "Uzum Bank", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 16_000_000, type: "to'liq", fields: ["Iqtisodiyot", "Marketing"], languages: ["en"], description: "SQL, Excel. Mijozlar segmentatsiyasi.", contact: "career@uzumbank.uz" }),

  // ============ MARKETING / SMM / DIZAYN ============
  j({ id: "mkt-1", title: "SMM mutaxassisi", company: "Korzinka.uz", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 12_000_000, type: "to'liq", remote: true, fields: ["Marketing", "Jurnalistika"], skills: ["smm", "kontent"], languages: ["uz", "ru"], description: "Instagram, TikTok, Telegram kontent strategiyasi.", contact: "hr@korzinka.uz" }),
  j({ id: "mkt-2", title: "Grafik dizayner", company: "Click", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 14_000_000, type: "to'liq", remote: true, skills: ["dizayner"], description: "Brendbook, vizual materiallar, motion graphics.", contact: "design@click.uz" }),
  j({ id: "mkt-3", title: "Video muharrir", company: "Mover.uz", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 13_000_000, type: "to'liq", skills: ["muharrir", "fotograf"], description: "Premiere Pro, After Effects. YouTube va reklama videolari.", contact: "@mover_uz" }),
  j({ id: "mkt-4", title: "Kontent menejer (Telegram)", company: "Daryo.uz", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "to'liq", remote: true, fields: ["Jurnalistika", "Marketing"], skills: ["smm", "kontent"], description: "Yangiliklar saytining Telegram kanalini olib borish.", contact: "career@daryo.uz" }),
  j({ id: "mkt-5", title: "Marketing menejer", company: "Texnomart", city: "Toshkent shahri", salaryFrom: 10_000_000, salaryTo: 18_000_000, type: "to'liq", fields: ["Marketing"], experienceYears: 2, languages: ["ru"], description: "Reklama kampaniyalarini boshqarish.", contact: "hr@texnomart.uz" }),
  j({ id: "mkt-6", title: "Fotograf (predmetli)", company: "Lebazar", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 11_000_000, type: "to'liq", skills: ["fotograf"], description: "Onlayn-do'kon uchun mahsulot fotosessiyasi.", contact: "@lebazar" }),
  j({ id: "mkt-7", title: "Copywriter (UZ/RU)", company: "Asaxiy.uz", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "to'liq", remote: true, fields: ["Filologiya", "Marketing", "Jurnalistika"], skills: ["kontent"], languages: ["uz", "ru"], description: "Mahsulot tavsiflari va reklama matnlari.", contact: "career@asaxiy.uz" }),
  j({ id: "mkt-8", title: "Targetolog (Facebook/Instagram Ads)", company: "Praktikum digital", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 15_000_000, type: "to'liq", remote: true, fields: ["Marketing"], skills: ["smm"], experienceYears: 1, description: "Meta Ads, TikTok Ads bo'yicha kampaniya boshqaruvi.", contact: "@praktikum_digital" }),
  j({ id: "mkt-9", title: "Brand designer", company: "Uzum Market", city: "Toshkent shahri", salaryFrom: 11_000_000, salaryTo: 19_000_000, type: "to'liq", remote: true, skills: ["dizayner"], experienceYears: 2, description: "Brand identity, illustration. Figma, Illustrator.", contact: "design@uzum.uz" }),
  j({ id: "mkt-10", title: "PR menejer", company: "Hilton Tashkent City", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 15_000_000, type: "to'liq", fields: ["Marketing", "Jurnalistika"], languages: ["en", "ru"], experienceYears: 1, description: "Brending, OAVlar bilan aloqalar.", contact: "hr@hilton.com" }),

  // ============ HUNAR — QURILISH / TEXNIKA ============
  j({ id: "skl-1", title: "Elektrik (3-4 razryad)", company: "UzAuto Motors", city: "Andijon", salaryFrom: 6_000_000, salaryTo: 9_500_000, type: "to'liq", skills: ["elektrik"], description: "Zavod elektr ta'minoti. Yotoqxona bor. Yosh kadrlarni o'rgatamiz.", contact: "+998 74 240 00 00" }),
  j({ id: "skl-2", title: "Payvandchi (svarka 5-razryad)", company: "Enter Engineering", city: "Buxoro", salaryFrom: 9_000_000, salaryTo: 15_000_000, type: "to'liq", skills: ["payvandchi"], experienceYears: 1, description: "Vaxta 28/14. Yotoqxona, ovqat tekin. Gaz quvurlari.", contact: "hr@enter.uz" }),
  j({ id: "skl-3", title: "Quruvchi (gips-karton, plitka)", company: "Murad Buildings", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 11_000_000, type: "to'liq", skills: ["quruvchi", "plitka"], description: "Yangi binolar pardozlash ishlari. Tushlik tekin.", contact: "+998 90 318 12 12" }),
  j({ id: "skl-4", title: "Santexnik", company: "Akfa Group", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", skills: ["santexnik"], description: "Yangi binolarda santexnika ishlari.", contact: "+998 71 200 50 50" }),
  j({ id: "skl-5", title: "Konditsioner ustasi", company: "Climate Tech", city: "Samarqand", salaryFrom: 7_000_000, salaryTo: 14_000_000, type: "to'liq", skills: ["kondisioner", "elektrik"], description: "Konditsionerlarni o'rnatish va xizmat ko'rsatish. Mashina beriladi.", contact: "+998 91 555 33 22" }),
  j({ id: "skl-6", title: "Bo'yoqchi (molyar)", company: "Akfa Group", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 9_000_000, type: "to'liq", skills: ["molyar"], description: "Bino ichki bo'yoq ishlari.", contact: "+998 71 200 50 50" }),
  j({ id: "skl-7", title: "Duradgor (mebel)", company: "Roison furniture", city: "Toshkent viloyati", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "to'liq", skills: ["duradgor"], description: "Buyurtmaga ko'ra mebel yasash. Transport tekin.", contact: "+998 90 234 11 22" }),
  j({ id: "skl-8", title: "Avtomexanik (Chevrolet)", company: "Chevrolet Service Plus", city: "Samarqand", salaryFrom: 6_000_000, salaryTo: 11_000_000, type: "to'liq", skills: ["avtomexanik"], description: "Yengil avtomobillarni ta'mirlash. O'rgatib boriladi.", contact: "+998 91 555 22 11" }),
  j({ id: "skl-9", title: "Telefon ustasi", company: "Premium Phone", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 10_000_000, type: "to'liq", skills: ["telefon-ustasi"], description: "iPhone, Samsung, Xiaomi ta'mirlash. Tezda o'rgatamiz.", contact: "+998 90 998 77 66" }),
  j({ id: "skl-10", title: "Tikuvchi (trikotaj fabrika)", company: "Global Textile", city: "Namangan", salaryFrom: 4_500_000, salaryTo: 8_000_000, type: "to'liq", skills: ["tikuvchi"], description: "Yangilarni o'rgatib boriladi. Tushlik tekin.", contact: "+998 69 555 11 22" }),
  j({ id: "skl-11", title: "Geolog (yosh)", company: "Navoiy Mining (NGMK)", city: "Navoiy", salaryFrom: 12_000_000, salaryTo: 18_000_000, type: "to'liq", fields: ["Geologiya", "Konchilik"], diplomaRequired: true, description: "Yotoqxona, ovqat, transport tekin. Konchilik ulushi.", contact: "hr@ngmk.uz" }),
  j({ id: "skl-12", title: "Mexanik (CNC operator)", company: "Artel", city: "Toshkent viloyati", salaryFrom: 6_500_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Mexanika", "Mashinasozlik"], description: "CNC stanok bilan ishlash. O'rgatamiz.", contact: "career@artel.uz" }),
  j({ id: "skl-13", title: "Junior muhandis-quruvchi", company: "Murad Buildings", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 13_000_000, type: "to'liq", fields: ["Qurilish", "Muhandislik"], diplomaRequired: true, description: "Bitiruvchi muhandislar uchun mentorlik.", contact: "hr@muradbuildings.uz" }),
  j({ id: "skl-14", title: "Energetika muhandisi", company: "Uzbekenergo", city: "Farg'ona", salaryFrom: 7_500_000, salaryTo: 12_000_000, type: "to'liq", fields: ["Muhandislik", "Energetika"], diplomaRequired: true, description: "Yuqori vol'tli liniyalar bo'yicha.", contact: "hr@energo.uz" }),
  j({ id: "skl-15", title: "Plitka ustasi", company: "Renovation Pro", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 14_000_000, type: "loyiha", skills: ["plitka", "quruvchi"], description: "Bitta xonadon — 1-3 hafta. Foiz asosida.", contact: "+998 99 222 44 55" }),
  j({ id: "skl-16", title: "Elektrik (uy-joy)", company: "Express Service", city: "Buxoro", salaryFrom: 5_500_000, salaryTo: 10_000_000, type: "to'liq", skills: ["elektrik"], description: "Uy va ofislarda chaqiruv bo'yicha. Mashina beriladi.", contact: "+998 65 224 88 77" }),
  j({ id: "skl-17", title: "Payvandchi (argon)", company: "AGMK (Olmaliq)", city: "Olmaliq", salaryFrom: 8_500_000, salaryTo: 14_000_000, type: "to'liq", skills: ["payvandchi"], experienceYears: 1, description: "Mis-eritma zavodi. Yotoqxona berilishi mumkin.", contact: "hr@agmk.uz" }),
  j({ id: "skl-18", title: "Mashinist (kran)", company: "Murad Buildings", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 12_000_000, type: "to'liq", experienceYears: 1, description: "Bashnyali kran. Sertifikat majburiy.", contact: "hr@muradbuildings.uz" }),
  j({ id: "skl-19", title: "Elektrik (zavod)", company: "Coca-Cola Bottlers Uzbekistan", city: "Toshkent viloyati", salaryFrom: 7_500_000, salaryTo: 11_000_000, type: "to'liq", skills: ["elektrik"], description: "Ishlab chiqarish liniyasini boshqarish. Transport tekin.", contact: "hr@coca-cola.uz" }),
  j({ id: "skl-20", title: "Tikuvchi (kostyumlar)", company: "Texka tikuvchilik", city: "Andijon", salaryFrom: 4_000_000, salaryTo: 7_500_000, type: "to'liq", skills: ["tikuvchi"], description: "Erkaklar kostyumlari. Ustaxonada ishlash.", contact: "+998 74 240 33 11" }),

  // ============ SERVIS / HORECA ============
  j({ id: "srv-1", title: "Oshpaz (milliy taomlar)", company: "Cafe Bahor", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 9_000_000, type: "to'liq", skills: ["oshpaz"], description: "Plov, sho'rva, lagman, manti. Tajriba shart emas.", contact: "+998 90 333 44 55" }),
  j({ id: "srv-2", title: "Bosh oshpaz (Yevropa taomlari)", company: "Hyatt Regency Tashkent", city: "Toshkent shahri", salaryFrom: 14_000_000, salaryTo: 22_000_000, type: "to'liq", skills: ["oshpaz"], experienceYears: 3, languages: ["en"], description: "Restoranning bosh oshpazi. Halqaro mehmonxona.", contact: "hr@hyatt.com" }),
  j({ id: "srv-3", title: "Barista", company: "Caffeine Coffee", city: "Toshkent shahri", salaryFrom: 5_000_000, salaryTo: 8_500_000, type: "to'liq", skills: ["ofitsiant"], description: "Coffee-shopda barista. Bepul o'qitish.", contact: "@caffeine_uz" }),
  j({ id: "srv-4", title: "Ofitsiant", company: "Beshqozon restorani", city: "Samarqand", salaryFrom: 4_500_000, salaryTo: 7_500_000, type: "to'liq", skills: ["ofitsiant"], languages: ["ru", "en"], description: "Restoranda mijozlarga xizmat. Chipta ham bor.", contact: "+998 91 444 55 66" }),
  j({ id: "srv-5", title: "Resepsion (Hotel)", company: "Hyatt Regency Tashkent", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Turizm"], languages: ["en", "ru"], description: "Mehmonlarni qabul qilish. B2+ ingliz tili.", contact: "hr@hyatt.com" }),
  j({ id: "srv-6", title: "Sartarosh (Barber)", company: "Brutal Barbershop", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 12_000_000, type: "to'liq", skills: ["sartarosh"], description: "Foiz asosida. Tajribasizlar uchun o'qitish.", contact: "@brutal_barbershop" }),
  j({ id: "srv-7", title: "Kosmetolog", company: "Estetic Beauty Center", city: "Toshkent shahri", salaryFrom: 7_500_000, salaryTo: 15_000_000, type: "to'liq", skills: ["kosmetolog"], description: "Sertifikat majburiy. Foiz asosida.", contact: "@estetic_beauty" }),
  j({ id: "srv-8", title: "Manikur ustasi", company: "Beauty Studio Lola", city: "Buxoro", salaryFrom: 5_000_000, salaryTo: 10_000_000, type: "to'liq", skills: ["manikur"], description: "Tirnoq dizayni. Foiz asosida.", contact: "+998 91 333 11 22" }),
  j({ id: "srv-9", title: "Fitnes trener", company: "Gym Sportlife", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 12_000_000, type: "to'liq", skills: ["fitnes"], description: "Shaxsiy trener. Sertifikat afzal.", contact: "@gym_sportlife" }),
  j({ id: "srv-10", title: "Administrator (Beauty salon)", company: "Privé Beauty", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", description: "Salonni boshqarish, mijozlar bilan ishlash.", contact: "+998 90 555 66 77" }),
  j({ id: "srv-11", title: "Oshpaz yordamchisi", company: "Korzinka Cafe", city: "Toshkent shahri", salaryFrom: 4_000_000, salaryTo: 6_000_000, type: "to'liq", skills: ["oshpaz"], description: "Tajriba shart emas. Bepul ovqat.", contact: "hr@korzinka.uz" }),
  j({ id: "srv-12", title: "Officer (mehmonxona)", company: "Wyndham Tashkent", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 9_500_000, type: "to'liq", fields: ["Turizm"], languages: ["en"], description: "Concierge bo'limi.", contact: "career@wyndham.com" }),

  // ============ HAYDOVCHI / LOGISTIKA / KURYER ============
  j({ id: "log-1", title: "Kuryer (avtomobil)", company: "Yandex Eats", city: "Toshkent shahri", salaryFrom: 5_000_000, salaryTo: 13_000_000, type: "to'liq", skills: ["kuryer", "haydovchi"], description: "Erkin grafik. Buyurtma soniga qarab daromad.", contact: "courier.yandex.uz" }),
  j({ id: "log-2", title: "Velosiped kuryer", company: "Express24", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 9_000_000, type: "to'liq", skills: ["kuryer"], description: "Markazda yetkazib berish. Tezkor narsalar.", contact: "@express24_uz" }),
  j({ id: "log-3", title: "Yuk mashinasi haydovchisi (C/E toifa)", company: "Uzauto Logistics", city: "Toshkent shahri", salaryFrom: 8_500_000, salaryTo: 14_000_000, type: "to'liq", skills: ["haydovchi"], experienceYears: 2, description: "Viloyatlararo yuklar. C va E toifa shart.", contact: "+998 71 200 66 11" }),
  j({ id: "log-4", title: "Taxi haydovchi (B toifa)", company: "MyTaxi", city: "Samarqand", salaryFrom: 5_500_000, salaryTo: 10_000_000, type: "to'liq", skills: ["haydovchi"], description: "Mashina beriladi yoki o'ziniki. Foiz: 80/20.", contact: "@mytaxi_uz" }),
  j({ id: "log-5", title: "Logistika menejer", company: "Korzinka.uz", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 14_000_000, type: "to'liq", fields: ["Logistika", "Transport"], experienceYears: 1, languages: ["ru"], description: "Yetkazib berish marshrutlarini boshqarish.", contact: "hr@korzinka.uz" }),
  j({ id: "log-6", title: "Omborchi", company: "Lebazar", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", description: "Omborda mahsulotlarni qabul/jo'natish.", contact: "@lebazar" }),
  j({ id: "log-7", title: "Yetkazib beruvchi (motosikl)", company: "Wolt Uzbekistan", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 14_000_000, type: "to'liq", skills: ["kuryer", "haydovchi"], description: "Mashinaning yoqilg'isi kompensatsiyalanadi.", contact: "courier@wolt.uz" }),
  j({ id: "log-8", title: "Taksi haydovchi (Yandex Go)", company: "Yandex Go", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 14_000_000, type: "to'liq", skills: ["haydovchi"], description: "B toifa, 21+ yosh. O'z mashinangiz yoki ijara.", contact: "yandex.com/yandexgo" }),
  j({ id: "log-9", title: "Avtobus haydovchi (D toifa)", company: "Toshkent Avtobus parki", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 9_000_000, type: "to'liq", skills: ["haydovchi"], experienceYears: 3, description: "Shahar marshrutlari. D toifa va 5+ yil staj.", contact: "+998 71 232 11 11" }),
  j({ id: "log-10", title: "Forklift operatori (avtokara)", company: "Coca-Cola Bottlers", city: "Toshkent viloyati", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", description: "Sertifikat majburiy. Tushlik tekin.", contact: "hr@coca-cola.uz" }),

  // ============ SAVDO / OPERATOR ============
  j({ id: "sl-1", title: "Sotuvchi-konsultant", company: "Texnomart", city: "Toshkent shahri", salaryFrom: 5_000_000, salaryTo: 9_000_000, type: "to'liq", skills: ["sotuvchi"], description: "Texnika do'koni. Foiz asosida bonus.", contact: "hr@texnomart.uz" }),
  j({ id: "sl-2", title: "Sotuvchi (kiyim-kechak)", company: "ZARA Uzbekistan", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", skills: ["sotuvchi"], description: "Yangi savdo markazlarida. O'qitish bepul.", contact: "@inditex.uz" }),
  j({ id: "sl-3", title: "Kassir-sotuvchi", company: "Magnum", city: "Samarqand", salaryFrom: 4_500_000, salaryTo: 6_500_000, type: "to'liq", skills: ["kassir", "sotuvchi"], description: "Supermarket. Smenali grafigi.", contact: "+998 91 555 22 11" }),
  j({ id: "sl-4", title: "Call-markaz operatori (UZ/RU)", company: "Beeline Uzbekistan", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 7_000_000, type: "to'liq", remote: true, skills: ["operator"], languages: ["uz", "ru"], description: "Tunda navbatchilik bor. Bonuslar.", contact: "career@beeline.uz" }),
  j({ id: "sl-5", title: "Online-konsultant (chat)", company: "Uzum Market", city: "Toshkent shahri", salaryFrom: 5_000_000, salaryTo: 8_000_000, type: "to'liq", remote: true, skills: ["operator"], languages: ["uz", "ru"], description: "Telegram va saytdagi chatlarda mijozlarga yordam.", contact: "support@uzum.uz" }),
  j({ id: "sl-6", title: "Menejer (B2B savdo)", company: "Akfa Group", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 16_000_000, type: "to'liq", fields: ["Marketing"], experienceYears: 1, description: "Korporativ mijozlar bilan ishlash. Foiz asosida.", contact: "career@akfagroup.com" }),
  j({ id: "sl-7", title: "Onlayn do'kon menejeri", company: "Asaxiy.uz", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_500_000, type: "to'liq", remote: true, fields: ["IT", "Marketing"], description: "Mahsulotlarni saytga joylash, kategoriyalar.", contact: "career@asaxiy.uz" }),
  j({ id: "sl-8", title: "Operator (1-sonli yo'l-poytaxt)", company: "Ucell", city: "Toshkent shahri", salaryFrom: 5_000_000, salaryTo: 7_500_000, type: "to'liq", skills: ["operator"], languages: ["uz", "ru"], description: "Mijozlarga xizmat ko'rsatish. Tunda navbat.", contact: "hr@ucell.uz" }),

  // ============ HUQUQ / TARJIMA / DIPLOMATIYA ============
  j({ id: "law-1", title: "Yurist yordamchisi", company: "Centil Law Firm", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 13_000_000, type: "to'liq", fields: ["Huquq"], languages: ["en", "ru"], diplomaRequired: true, description: "Hujjatlar tahlili, sud jarayonlariga tayyorgarlik.", contact: "hr@centil.law" }),
  j({ id: "law-2", title: "Notarius yordamchisi", company: "Davlat notarial idorasi", city: "Buxoro", salaryFrom: 5_000_000, salaryTo: 7_500_000, type: "to'liq", fields: ["Huquq"], diplomaRequired: true, description: "Hujjatlarni tayyorlash, mijozlar bilan ishlash.", contact: "+998 65 224 11 11" }),
  j({ id: "law-3", title: "Korporativ yurist", company: "Akfa Group", city: "Toshkent shahri", salaryFrom: 10_000_000, salaryTo: 18_000_000, type: "to'liq", fields: ["Huquq"], languages: ["en", "ru"], experienceYears: 2, diplomaRequired: true, description: "Shartnomalar, biznes-litsenziyalar.", contact: "career@akfagroup.com" }),
  j({ id: "tr-1", title: "Tarjimon (ingliz-o'zbek)", company: "Wooppay", city: "Toshkent shahri", salaryFrom: 6_000_000, salaryTo: 10_000_000, type: "yarim", remote: true, fields: ["Tillar", "Tarjima"], languages: ["en"], description: "Texnik hujjatlar va veb-sayt tarjimasi.", contact: "career@wooppay.com" }),
  j({ id: "tr-2", title: "Sinxron tarjimon (ingliz)", company: "UWED universiteti", city: "Toshkent shahri", salaryFrom: 12_000_000, salaryTo: 20_000_000, type: "loyiha", fields: ["Tillar", "Tarjima"], languages: ["en"], experienceYears: 2, description: "Konferensiyalar uchun sinxron. C1+ ingliz tili.", contact: "hr@uwed.uz" }),
  j({ id: "tr-3", title: "Yapon tili tarjimoni", company: "JICA Uzbekistan", city: "Toshkent shahri", salaryFrom: 10_000_000, salaryTo: 16_000_000, type: "to'liq", fields: ["Tillar", "Tarjima"], languages: ["ja"], experienceYears: 1, description: "Yaponiya kompaniyalari bilan ishlash.", contact: "hr@jica.go.jp" }),
  j({ id: "tr-4", title: "Tarjimon-administrator (koreys)", company: "Korea Business Center", city: "Toshkent shahri", salaryFrom: 8_500_000, salaryTo: 13_000_000, type: "to'liq", fields: ["Tillar"], languages: ["ko"], description: "Koreys kompaniyalari bilan ishlash, viza yordami.", contact: "@korea_business_uz" }),
  j({ id: "tr-5", title: "Turk tili tarjimoni", company: "Anadolu Group", city: "Toshkent shahri", salaryFrom: 7_500_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Tillar", "Tarjima"], languages: ["tr"], description: "Turk kompaniyasi. Hujjat tarjimasi va majlislar.", contact: "+998 71 200 80 80" }),
  j({ id: "tr-6", title: "Xitoy tili tarjimoni", company: "China Railway 7th Group", city: "Qarshi", salaryFrom: 11_000_000, salaryTo: 18_000_000, type: "to'liq", fields: ["Tillar", "Tarjima"], languages: ["zh"], description: "Qurilish loyihalarida. Yotoqxona bor.", contact: "+998 75 224 11 22" }),

  // ============ QISHLOQ XO'JALIGI / SANOAT ============
  j({ id: "agr-1", title: "Agronom yordamchisi", company: "Agrofermer Cluster", city: "Jizzax", salaryFrom: 6_000_000, salaryTo: 9_000_000, type: "to'liq", fields: ["Qishloq xo'jaligi", "Agronomiya"], skills: ["dehqon"], description: "Paxta va g'alla maydonlari. Mashina beriladi.", contact: "+998 72 226 33 44" }),
  j({ id: "agr-2", title: "Veterinar (chorvachilik)", company: "Sayyod meat", city: "Toshkent viloyati", salaryFrom: 7_000_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Veterinariya"], diplomaRequired: true, description: "Yirik fermada veterinariya nazorati.", contact: "+998 90 444 33 22" }),
  j({ id: "agr-3", title: "Issiqxona ishchisi", company: "Green Valley", city: "Samarqand viloyati", salaryFrom: 5_000_000, salaryTo: 8_000_000, type: "to'liq", skills: ["dehqon"], description: "Pomidor, bodring. Yotoqxona bor.", contact: "+998 66 233 55 11" }),
  j({ id: "agr-4", title: "Asalarichi", company: "Bal-Mahsulot", city: "Farg'ona", salaryFrom: 4_500_000, salaryTo: 7_500_000, type: "to'liq", skills: ["dehqon"], description: "Asalarichilik. Tajriba shart emas, o'rgatamiz.", contact: "+998 73 244 11 22" }),

  // ============ TURIZM / GIDLAR ============
  j({ id: "tur-1", title: "Tarjimon-gid", company: "Asia Adventures", city: "Samarqand", salaryFrom: 8_000_000, salaryTo: 15_000_000, type: "loyiha", fields: ["Turizm", "Tillar"], languages: ["en"], experienceYears: 1, description: "Yevropa va Amerika sayyohlariga sayohatlar.", contact: "@asia_adventures" }),
  j({ id: "tur-2", title: "Tur menejer (ofis)", company: "Advantour", city: "Toshkent shahri", salaryFrom: 6_500_000, salaryTo: 10_000_000, type: "to'liq", fields: ["Turizm"], languages: ["en", "ru"], description: "Sayohat paketlari sotish, mijozlar bilan ishlash.", contact: "career@advantour.com" }),
  j({ id: "tur-3", title: "Concierge", company: "Hilton Tashkent", city: "Toshkent shahri", salaryFrom: 7_500_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Turizm"], languages: ["en"], description: "Mehmonlarga shahar bo'ylab maslahat.", contact: "hr@hilton.com" }),

  // ============ AMALIYOT / INTERNSHIP ============
  j({ id: "int-1", title: "Marketing intern", company: "Coca-Cola Bottlers", city: "Toshkent shahri", salaryFrom: 3_500_000, salaryTo: 4_500_000, type: "amaliyot", fields: ["Marketing"], languages: ["en"], description: "3 oylik amaliyot. Eng yaxshilar ishga olinadi.", contact: "hr@coca-cola.uz" }),
  j({ id: "int-2", title: "Finance intern", company: "Ernst & Young Uzbekistan", city: "Toshkent shahri", salaryFrom: 4_000_000, salaryTo: 6_000_000, type: "amaliyot", fields: ["Iqtisodiyot", "Moliya"], languages: ["en"], diplomaRequired: false, description: "Big-4 da amaliyot. Bitiruvchilar uchun.", contact: "career@ey.uz" }),
  j({ id: "int-3", title: "Jurnalist-stajor", company: "Kun.uz", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 6_500_000, type: "amaliyot", fields: ["Jurnalistika"], description: "Yangiliklar yozish. Yaxshilari shtatga olinadi.", contact: "@kun_uz" }),

  // ============ HR / AMINISTRATIVE ============
  j({ id: "hr-1", title: "HR menejer (junior)", company: "Uzum Holding", city: "Toshkent shahri", salaryFrom: 7_000_000, salaryTo: 11_000_000, type: "to'liq", fields: ["Psixologiya"], languages: ["ru"], description: "Onbording, intervyu, kadrlar bo'limi.", contact: "hr@uzum.uz" }),
  j({ id: "hr-2", title: "Recruiter (IT)", company: "EPAM Uzbekistan", city: "Toshkent shahri", salaryFrom: 9_000_000, salaryTo: 16_000_000, type: "to'liq", remote: true, languages: ["en"], description: "IT mutaxassislarini izlash. LinkedIn Recruiter.", contact: "career@epam.uz" }),
  j({ id: "hr-3", title: "Ofis menejer", company: "Anor Bank", city: "Toshkent shahri", salaryFrom: 5_500_000, salaryTo: 8_000_000, type: "to'liq", description: "Ofisni boshqarish, hujjatlar.", contact: "hr@anorbank.uz" }),
  j({ id: "hr-4", title: "Sekretar-referent", company: "TIIAME", city: "Toshkent shahri", salaryFrom: 4_500_000, salaryTo: 6_500_000, type: "to'liq", languages: ["ru"], diplomaRequired: true, description: "Rektorat sekretarligi. Davlat universiteti.", contact: "hr@tiiame.uz" }),

  // ============ CHET ELDA ISHLASH (REKLAMA) ============
  j({ id: "abr-1", title: "Janubiy Koreya — EPS dasturi", company: "Mehnat vazirligi", city: "Toshkent shahri", salaryFrom: 1500, salaryTo: 2500, currency: "USD", type: "to'liq", description: "Koreyaning sanoat sektoriga 3 yillik kontrakt. Til imtihon va sog'liq talab.", contact: "https://mehnat.uz/eps" }),
  j({ id: "abr-2", title: "Yaponiya — Specified Skilled Worker", company: "JICA Uzbekistan", city: "Toshkent shahri", salaryFrom: 1800, salaryTo: 3000, currency: "USD", type: "to'liq", languages: ["ja"], description: "Yaponiya tilini N4 darajada bilish. Sanoat va xizmat sohasi.", contact: "hr@jica.go.jp" }),
  j({ id: "abr-3", title: "Germaniya — tibbiyot xodimlari", company: "Mehnat agentligi", city: "Toshkent shahri", salaryFrom: 2200, salaryTo: 3500, currency: "USD", type: "to'liq", fields: ["Tibbiyot"], skills: ["hamshira"], languages: ["de"], diplomaRequired: true, description: "Nemis tilini B2 darajada bilish. Tibbiyot diplomi.", contact: "https://mehnat.uz/germany" }),

  // ============ HUKUMAT VA KAMSITISH IMTIYOZLARI ============
  j({ id: "gov-1", title: "Davlat xizmatchisi (Yoshlar Daftari)", company: "Yoshlar Markazlari Agentligi", city: "Buxoro", salaryFrom: 5_500_000, salaryTo: 8_500_000, type: "to'liq", fields: ["Psixologiya", "Pedagogika"], diplomaRequired: true, description: "Yoshlar bilan ishlash. Davlat xizmati.", contact: "yoshlar@buxoro.uz" }),
  j({ id: "gov-2", title: "IT mutaxassis (Tashqi ishlar vazirligi)", company: "Tashqi ishlar vazirligi", city: "Toshkent shahri", salaryFrom: 8_000_000, salaryTo: 13_000_000, type: "to'liq", fields: ["IT"], diplomaRequired: true, languages: ["en"], description: "Davlat sayti va ichki tizimlar.", contact: "hr@mfa.uz" }),
];

// Filtrlar uchun helper'lar
export const JOB_FIELDS = Array.from(new Set(JOBS.flatMap((j) => j.fields))).sort();
export const JOB_CITIES = Array.from(new Set(JOBS.map((j) => j.city))).sort();
